function A = get_A_transv(s,s_dot,phi1,phi_prm1,phi_2prm1)
%GET_A_TRANSV
%    A = GET_A_TRANSV(S,S_DOT,PHI1,PHI_PRM1,PHI_2PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:34

t2 = cos(phi1);
t3 = sin(phi1);
t4 = phi1+s;
t5 = s_dot.^2;
t6 = phi_prm1.*(1.1e+1./1.2e+1);
t7 = phi_2prm1.*(1.1e+1./1.2e+1);
t8 = t3+t7;
t9 = t2+t6+1.1e+1./1.2e+1;
t10 = 1.0./t9;
A = reshape([s_dot.*t8.*t10.*-2.0,0.0,0.0,s_dot.*t10.*(cos(t4).*(9.8e+1./5.0)+t2.*t5+t3.*t10.*(sin(t4).*(9.8e+1./5.0)+t5.*t8)).*-2.0,0.0,0.0,0.0,1.0,0.0],[3,3]);
