function alpha = get_alpha(in1,in2)
%GET_ALPHA
%    ALPHA = GET_ALPHA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:33

phi2 = in1(2,:);
phi1_prm = in2(1,:);
phi2_prm = in2(2,:);
alpha = phi2_prm.*(1.1e+1./1.2e+1)+phi1_prm.*(cos(phi2)+1.1e+1./1.2e+1);
