function g = g_dynamics_g(in1)
%G_DYNAMICS_G
%    G = G_DYNAMICS_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:22

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = sin(t2);
t4 = t3.*(4.9e+1./2.0);
g = [t4+sin(q1).*(1.47e+2./2.0);t4];
