function gamma = get_gamma(in1)
%GET_GAMMA
%    GAMMA = GET_GAMMA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:23

phi1 = in1(1,:);
phi2 = in1(2,:);
gamma = sin(phi1+phi2).*(4.9e+1./2.0);
