function N = get_N(s,y1,phi1,phi_prm1)
%GET_N
%    N = GET_N(S,Y1,PHI1,PHI_PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:24

t2 = phi1+y1;
t3 = cos(t2);
t4 = t3.^2;
t5 = t4.*3.6e+1;
t6 = t5-8.5e+1;
t7 = 1.0./t6;
N = t7.*(t3.*6.0+5.0).*(2.4e+1./5.0)+phi_prm1.*t7.*2.4e+1;
