function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:27

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*(3.0./2.0);
t4 = t3+7.0./6.0;
H = reshape([t2.*3.0+1.25e+2./2.4e+1,t4,t4,7.0./6.0],[2,2]);
