function C = g_dynamics_C(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:27

q2 = in1(2,:);
v1 = in2(1,:);
v2 = in2(2,:);
t2 = sin(q2);
C = reshape([t2.*v2.*(-3.0./2.0),t2.*v1.*(3.0./2.0),t2.*(v1+v2).*(-3.0./2.0),0.0],[2,2]);
