function N = get_N(s,y1,phi1,phi_prm1)
%GET_N
%    N = GET_N(S,Y1,PHI1,PHI_PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:29

t2 = phi1+y1;
t3 = cos(t2);
t4 = t3.^2;
t5 = t4.*3.24e+2;
t6 = t5-6.79e+2;
t7 = 1.0./t6;
N = t7.*(t3.*9.0+7.0).*2.4e+1+phi_prm1.*t7.*1.68e+2;
