function A = get_A_transv(s,s_dot,phi1,phi_prm1,phi_2prm1)
%GET_A_TRANSV
%    A = GET_A_TRANSV(S,S_DOT,PHI1,PHI_PRM1,PHI_2PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:29

t2 = cos(phi1);
t3 = sin(phi1);
t4 = phi1+s;
t5 = phi_prm1.*7.0;
t6 = s_dot.^2;
t7 = t2.*9.0;
t8 = t5+t7+7.0;
t9 = 1.0./t8;
A = reshape([s_dot.*t9.*(phi_2prm1.*7.0+t3.*9.0).*-2.0,0.0,0.0,s_dot.*t9.*(cos(t4).*(1.47e+2./5.0)+t2.*t6.*(3.0./2.0)+(t3.*(sin(t4).*(1.47e+2./5.0)+t6.*(phi_2prm1.*(7.0./6.0)+t3.*(3.0./2.0))).*(3.0./2.0))./(phi_prm1.*(7.0./6.0)+t2.*(3.0./2.0)+7.0./6.0)).*-1.2e+1,0.0,0.0,0.0,1.0,0.0],[3,3]);
