function U = get_U_ff(s,s_dot,y1,y_dot1,phi1,phi_prm1,phi_2prm1)
%GET_U_FF
%    U = GET_U_FF(S,S_DOT,Y1,Y_DOT1,PHI1,PHI_PRM1,PHI_2PRM1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:26

t2 = phi_prm1.*s_dot;
t3 = phi1+y1;
t4 = s_dot.^2;
t5 = cos(t3);
t6 = s+t3;
t7 = sin(t3);
t11 = s_dot+t2+y_dot1;
t8 = sin(t6);
t9 = t5.*6.0;
t10 = t5.^2;
t12 = t9+5.0;
t13 = t10.*9.0;
t14 = t8.*(4.9e+1./2.0);
t15 = t13-2.2e+1;
t16 = 1.0./t15;
t17 = phi_prm1.*t16.*6.0;
t18 = t12.*t16.*(6.0./5.0);
t19 = t17+t18;
U = (-(t14+t4.*t7.*(5.0./4.0)).*(t16.*(t5.*6.0e+1+1.13e+2).*(6.0./2.5e+1)+phi_prm1.*t18)+phi_2prm1.*t4+t19.*(t14+sin(s).*(3.92e+2./5.0)-s_dot.*(t7.*(t2+y_dot1).*(5.0./4.0)+phi_prm1.*t7.*t11.*(5.0./4.0))-t7.*t11.*y_dot1.*(5.0./4.0)))./t19;
