function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 16:18:32

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2+1.1e+1./1.2e+1;
H = reshape([t2.*2.0+9.5e+1./2.4e+1,t3,t3,1.1e+1./1.2e+1],[2,2]);
